### ISSUE TITLE
有点问题呢,fpdi类没有引入呀

### ISSUE THREAD

**Issue by mYangFan** [ColorRabbit/PpfWatermarker#1]

**Comment by ColorRabbit** [comment]
依赖问题 已经解决

**Comment by mYangFan** [comment]
这个是默认装了fpdi依赖吗

**Comment by ColorRabbit** [comment]
不好意思，才看见。
fpdi还是需要自己安装下呢！
或者项目下载下来 直接composer installer一下即可，不过可能要科学上网，不然比较慢，自己的包，资源比较差。

或者官网直接下载
http://www.fpdf.org
fpdi可以单独使用composer单独下载，不需要使用我的composer文件
